configuration = {
    "SETUP_FILE": "medium_testsetup.txt",
    "SIMULATION_RUNS": 1,
    "SIMULATION_RANGE": 2500,
    "SEED_MACHINE_INTERRUPTIONS": 29378374,
    "MACHINE_FAILURE_RATE": 20,
    "FAILURE_MINIMAL_LENGTH": 20,
    "FAILURE_MAXIMAL_LENGTH": 50,
    "SEED_INCOMING_ORDERS": 10278347,
    "NUMBER_OF_ORDERS": 50,
    "ORDER_MINIMAL_LENGTH": 200,
    "ORDER_MAXIMAL_LENGTH": 300,
    "SPREAD_ORDER_COMPLEXITY": 0.1,
    "AGENT_SPEED": 1,
    "AGENT_LONGEST_WAITING_TIME": 10,
    "MACHINE_SETUP_TIME": 5,
    "DB_IN_MEMORY": True,
    "TIME_FOR_ITEM_PICK_UP": 0.1,
    "TIME_FOR_ITEM_STORE": 0.1,

    "DISTANCES": {
        "BASE_HEIGHT": 1,
        "BASE_WIDTH": 1,
        "INTERFACE_DISTANCE": 1,
        "DISTANCE_BETWEEN_CELLS": 0.5,
        "MULTIPLICATOR_UPPER_CELL": 1, # Derzeit keine extremen Werte möglich!
        "MULTIPLICATOR_LOWER_CELL": 1
    }

}
